--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 203, in setup
    logger.info("PyCaret Supervised Module")
Message: 'PyCaret Supervised Module'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 204, in setup
    logger.info(f"ML Usecase: {ml_usecase}")
Message: 'ML Usecase: anomaly'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 205, in setup
    logger.info(f"version {ver}")
Message: 'version 2.3.5'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 206, in setup
    logger.info("Initializing setup()")
Message: 'Initializing setup()'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 207, in setup
    logger.info(f"setup({function_params_str})")
Message: "setup(target=None, ml_usecase=anomaly, available_plots={'tsne': 'Anomaly TSnE (3d)', 'umap': 'UMAP Dimensionality'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=mode, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=False, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=False, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=123, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=True, verbose=True, profile=False, profile_kwargs=None, display=None)"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 210, in setup
    logger.info("Checking environment")
Message: 'Checking environment'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 214, in setup
    logger.info(f"python_version: {python_version()}")
Message: 'python_version: 3.7.1'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 215, in setup
    logger.info(f"python_build: {python_build()}")
Message: "python_build: ('v3.7.1:260ec2c36a', 'Oct 20 2018 14:57:15')"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 216, in setup
    logger.info(f"machine: {machine()}")
Message: 'machine: AMD64'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 217, in setup
    logger.info(f"platform: {platform()}")
Message: 'platform: Windows-10-10.0.19041-SP0'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 222, in setup
    logger.info(f"Memory: {psutil.virtual_memory()}")
Message: 'Memory: svmem(total=17024389120, available=7888035840, percent=53.7, used=9136353280, free=7888035840)'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 223, in setup
    logger.info(f"Physical Core: {psutil.cpu_count(logical=False)}")
Message: 'Physical Core: 4'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 224, in setup
    logger.info(f"Logical Core: {psutil.cpu_count(logical=True)}")
Message: 'Logical Core: 8'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 230, in setup
    logger.info("Checking libraries")
Message: 'Checking libraries'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 235, in setup
    logger.info(f"pd=={__version__}")
Message: 'pd==1.3.0'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 242, in setup
    logger.info(f"numpy=={__version__}")
Message: 'numpy==1.19.5'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 249, in setup
    logger.info(f"sklearn=={__version__}")
Message: 'sklearn==0.23.2'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 262, in setup
    logger.info(f"lightgbm=={__version__}")
Message: 'lightgbm==3.3.2'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 269, in setup
    logger.info(f"catboost=={__version__}")
Message: 'catboost==1.0.4'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 276, in setup
    logger.info(f"xgboost=={__version__}")
Message: 'xgboost==1.5.2'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 284, in setup
    logger.info(f"mlflow=={VERSION}")
Message: 'mlflow==1.18.0'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 291, in setup
    logger.info("Checking Exceptions")
Message: 'Checking Exceptions'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 778, in setup
    logger.info("Declaring global variables")
Message: 'Declaring global variables'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 782, in setup
    logger.info(f"USI: {USI}")
Message: 'USI: 8657'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 838, in setup
    logger.info(f"pycaret_globals: {pycaret_globals}")
Message: "pycaret_globals: {'experiment__', 'target_param', 'pycaret_globals', 'create_model_container', 'fold_shuffle_param', 'X', 'fold_groups_param', '_internal_pipeline', '_all_metrics', 'transform_target_param', 'display_container', 'gpu_param', '_all_models', 'fold_param', '_ml_usecase', 'fix_imbalance_param', 'imputation_classifier', 'seed', 'imputation_regressor', '_available_plots', 'USI', 'exp_name_log', 'fold_groups_param_full', 'prep_pipe', 'transform_target_method_param', '_gpu_n_jobs_param', 'master_model_container', 'log_plots_param', 'iterative_imputation_iters_param', 'html_param', 'fix_imbalance_method_param', 'stratify_param', 'fold_generator', '_all_models_internal', 'n_jobs_param', 'data_before_preprocess', 'logging_param'}"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 843, in setup
    logger.info("Preparing display monitor")
Message: 'Preparing display monitor'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 859, in setup
    monitor_rows=monitor_rows,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\Display.py", line 162, in __init__
    self.logger.info("Preparing display monitor")
Message: 'Preparing display monitor'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 865, in setup
    logger.info("Importing libraries")
Message: 'Importing libraries'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 881, in setup
    logger.info("Copying data for preprocessing")
Message: 'Copying data for preprocessing'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 902, in setup
    logger.info("Declaring preprocessing parameters")
Message: 'Declaring preprocessing parameters'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1137, in setup
    logger.info("Creating preprocessing pipeline")
Message: 'Creating preprocessing pipeline'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1202, in setup
    logger.info("Preprocessing pipeline created successfully")
Message: 'Preprocessing pipeline created successfully'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1206, in setup
    res = dtypes.response
AttributeError: 'DataTypes_Auto_infer' object has no attribute 'response'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1215, in setup
    "(Process Exit): setup has been interupted with user command 'quit'. setup must rerun."
Message: "(Process Exit): setup has been interupted with user command 'quit'. setup must rerun."
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1229, in setup
    logger.info("Creating global containers")
Message: 'Creating global containers'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1322, in setup
    logger.info(f"Internal pipeline: {_internal_pipeline}")
Message: "Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1469, in setup
    logger.info("Creating grid variables")
Message: 'Creating grid variables'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1804, in setup
    logger.info(f"create_model_container: {len(create_model_container)}")
Message: 'create_model_container: 0'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1805, in setup
    logger.info(f"master_model_container: {len(master_model_container)}")
Message: 'master_model_container: 0'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1806, in setup
    logger.info(f"display_container: {len(display_container)}")
Message: 'display_container: 1'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1808, in setup
    logger.info(str(prep_pipe))
Message: "Pipeline(memory=None,\n         steps=[('dtypes',\n                 DataTypes_Auto_infer(categorical_features=[],\n                                      display_types=False, features_todrop=[],\n                                      id_columns=[], ml_usecase='regression',\n                                      numerical_features=[],\n                                      target='UNSUPERVISED_DUMMY_TARGET',\n                                      time_features=[])),\n                ('imputer',\n                 Simple_Imputer(categorical_strategy='most frequent',\n                                fill_value_categorical=None,\n                                fill_value_numerical=Non...\n                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),\n                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),\n                ('cluster_all', 'passthrough'),\n                ('dummy', Dummify(target='UNSUPERVISED_DUMMY_TARGET')),\n                ('fix_perfect', 'passthrough'),\n                ('clean_names', Clean_Colum_Names()),\n                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),\n                ('dfs', 'passthrough'), ('pca', 'passthrough')],\n         verbose=False)"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 36, in CaretModel
    s = setup(data, session_id=123, silent=True,n_jobs=-1)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 438, in setup
    profile_kwargs=profile_kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 1809, in setup
    logger.info("setup() succesfully completed......................................")
Message: 'setup() succesfully completed......................................'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 38, in CaretModel
    for modelname in models().index.tolist():
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 1103, in models
    return pycaret.internal.tabular.models(internal=internal, raise_errors=raise_errors)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 9582, in models
    logger.info(f"gpu_param set to {gpu_param}")
Message: 'gpu_param set to False'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2512, in create_model_unsupervised
    logger.info("Initializing create_model()")
Message: 'Initializing create_model()'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2513, in create_model_unsupervised
    logger.info(f"create_model({function_params_str})")
Message: 'create_model(estimator=iforest, num_clusters=4, fraction=0.04, ground_truth=None, round=4, fit_kwargs=None, verbose=True, system=True, add_to_model_list=True, raise_num_clusters=False, display=None, kwargs={})'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2515, in create_model_unsupervised
    logger.info("Checking exceptions")
Message: 'Checking exceptions'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2587, in create_model_unsupervised
    monitor_rows=monitor_rows,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\Display.py", line 162, in __init__
    self.logger.info("Preparing display monitor")
Message: 'Preparing display monitor'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2593, in create_model_unsupervised
    logger.info("Importing libraries")
Message: 'Importing libraries'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2611, in create_model_unsupervised
    logger.info("Importing untrained model")
Message: 'Importing untrained model'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2653, in create_model_unsupervised
    logger.info(f"{full_name} Imported succesfully")
Message: 'Isolation Forest Imported succesfully'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2672, in create_model_unsupervised
    logger.info("Fitting Model")
Message: 'Fitting Model'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2708, in create_model_unsupervised
    logger.info(str(model))
Message: "IForest(behaviour='new', bootstrap=False, contamination=0.04,\n    max_features=1.0, max_samples='auto', n_estimators=100, n_jobs=-1,\n    random_state=123, verbose=0)"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2710, in create_model_unsupervised
    "create_models() succesfully completed......................................"
Message: 'create_models() succesfully completed......................................'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2738, in create_model_unsupervised
    logger.info("Uploading results into container")
Message: 'Uploading results into container'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2750, in create_model_unsupervised
    logger.info("Uploading model into container now")
Message: 'Uploading model into container now'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2760, in create_model_unsupervised
    logger.info(f"create_model_container: {len(create_model_container)}")
Message: 'create_model_container: 1'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2761, in create_model_unsupervised
    logger.info(f"master_model_container: {len(master_model_container)}")
Message: 'master_model_container: 1'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2762, in create_model_unsupervised
    logger.info(f"display_container: {len(display_container)}")
Message: 'display_container: 2'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2764, in create_model_unsupervised
    logger.info(str(model))
Message: "IForest(behaviour='new', bootstrap=False, contamination=0.04,\n    max_features=1.0, max_samples='auto', n_estimators=100, n_jobs=-1,\n    random_state=123, verbose=0)"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 40, in CaretModel
    modelend = create_model(modelname, fraction = fraction)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 510, in create_model
    **kwargs,
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 2766, in create_model_unsupervised
    "create_model() succesfully completed......................................"
Message: 'create_model() succesfully completed......................................'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 41, in CaretModel
    iforest_results = assign_model(modelend)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 554, in assign_model
    model, transformation=transformation, score=score, verbose=verbose
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 8459, in assign_model
    logger.info("Initializing assign_model()")
Message: 'Initializing assign_model()'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 41, in CaretModel
    iforest_results = assign_model(modelend)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 554, in assign_model
    model, transformation=transformation, score=score, verbose=verbose
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 8460, in assign_model
    logger.info(f"assign_model({function_params_str})")
Message: "assign_model(model=IForest(behaviour='new', bootstrap=False, contamination=0.04,\n    max_features=1.0, max_samples='auto', n_estimators=100, n_jobs=-1,\n    random_state=123, verbose=0), transformation=False, score=True, verbose=True)"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 41, in CaretModel
    iforest_results = assign_model(modelend)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 554, in assign_model
    model, transformation=transformation, score=score, verbose=verbose
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 8462, in assign_model
    logger.info("Checking exceptions")
Message: 'Checking exceptions'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 41, in CaretModel
    iforest_results = assign_model(modelend)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 554, in assign_model
    model, transformation=transformation, score=score, verbose=verbose
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 8481, in assign_model
    logger.info("Determining Trained Model")
Message: 'Determining Trained Model'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 41, in CaretModel
    iforest_results = assign_model(modelend)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 554, in assign_model
    model, transformation=transformation, score=score, verbose=verbose
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 8485, in assign_model
    logger.info(f"Trained Model : {name}")
Message: 'Trained Model : Isolation Forest'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 41, in CaretModel
    iforest_results = assign_model(modelend)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 554, in assign_model
    model, transformation=transformation, score=score, verbose=verbose
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 8487, in assign_model
    logger.info("Copying data")
Message: 'Copying data'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 41, in CaretModel
    iforest_results = assign_model(modelend)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 554, in assign_model
    model, transformation=transformation, score=score, verbose=verbose
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 8507, in assign_model
    logger.info(data.shapMessage: (5590, 9)
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\balug\appdata\local\programs\python\python37\lib\logging\__init__.py", line 1036, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\balug\appdata\local\programs\python\python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 200, in _process_request_queue
    self._run_script(data)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\streamlit\script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\app.py", line 38, in <module>
    page2.app(db,UserClass,name)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 771, in app
    anomaly()
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\pages\page2.py", line 638, in anomaly
    result = ad.CaretModel(data, modelname, fraction)
  File "C:\Users\balug\OneDrive\Masaüstü\Veri Bilimi Çalýþmalarý\Auto-ML\AnomalyDetection.py", line 41, in CaretModel
    iforest_results = assign_model(modelend)
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\anomaly.py", line 554, in assign_model
    model, transformation=transformation, score=score, verbose=verbose
  File "c:\users\balug\appdata\local\programs\python\python37\lib\site-packages\pycaret\internal\tabular.py", line 8509, in assign_model
    "assign_model() succesfully completed......................................"
Message: 'assign_model() succesfully completed......................................'
Arguments: ()
()
